FROM postgres:9.6
USER root
ENV IS_RESUME="true"
COPY dependencies/psql_dump.sql ./docker-entrypoint-initdb.d/dbinit.sql
COPY dependencies/hive-schema-2.3.0.postgres.sql ./docker-entrypoint-initdb.d/hive-schema-2.3.0.postgres.sql
COPY dependencies/hive-txn-schema-2.3.0.postgres.sql ./docker-entrypoint-initdb.d/hive-txn-schema-2.3.0.postgres.sql